create table if not exists public.webhook_events (
  id bigint generated by default as identity primary key,

  provider text not null default 'cloudpayments',

  event_type text not null,

  idempotency_key text not null,

  payment_id bigint
    references public.payments(id)
    on delete set null,

  invoice_id text,
  provider_transaction_id bigint,
  provider_subscription_id text,

  status text not null default 'received'
    check (
      status in (
        'received',
        'processing',
        'processed',
        'failed',
        'ignored'
      )
    ),

  payload jsonb not null,

  error_message text,

  received_at timestamptz not null default now(),
  processed_at timestamptz,

  constraint webhook_events_idempotency_unique
    unique (provider, idempotency_key)
);

create index if not exists webhook_events_payment_id_idx
  on public.webhook_events(payment_id);

create index if not exists webhook_events_invoice_id_idx
  on public.webhook_events(invoice_id);

create index if not exists webhook_events_provider_transaction_id_idx
  on public.webhook_events(provider_transaction_id);

create index if not exists webhook_events_status_idx
  on public.webhook_events(status);

create index if not exists webhook_events_received_at_idx
  on public.webhook_events(received_at desc);

alter table public.webhook_events enable row level security;