create unique index if not exists notifications_forecast_card_id_unique
on public.notifications (forecast_card_id)
where forecast_card_id is not null;

alter table public.notifications
add column if not exists match_time timestamptz,
add column if not exists coefficient numeric(8, 2);

alter table public.notifications
alter column coefficient set default 0;

update public.notifications n
set
  match_time = fc.start_time,
  coefficient = coalesce(fc.total_odds, 0)
from public.forecast_cards fc
where fc.id = n.forecast_card_id;

update public.notifications
set coefficient = 0
where coefficient is null;

alter table public.notifications
alter column coefficient set not null;

create table if not exists public.user_live_prediction_assignments (
  id bigint generated by default as identity primary key,

  user_id uuid not null
    references auth.users(id)
    on delete cascade,

  live_prediction_id bigint not null
    references public.live_predictions(id)
    on delete cascade,

  notification_id bigint
    references public.notifications(id)
    on delete set null,

  created_at timestamptz not null default now(),

  constraint user_live_prediction_assignments_user_prediction_unique
    unique (user_id, live_prediction_id)
);

create index if not exists idx_user_live_prediction_assignments_user_id
  on public.user_live_prediction_assignments(user_id);

create index if not exists idx_user_live_prediction_assignments_live_prediction_id
  on public.user_live_prediction_assignments(live_prediction_id);

create index if not exists idx_user_live_prediction_assignments_notification_id
  on public.user_live_prediction_assignments(notification_id)
  where notification_id is not null;

alter table public.user_live_prediction_assignments enable row level security;

drop policy if exists "Users can view own live prediction assignments"
on public.user_live_prediction_assignments;

create policy "Users can view own live prediction assignments"
on public.user_live_prediction_assignments
for select
to authenticated
using ((select auth.uid()) = user_id);

insert into public.user_live_prediction_assignments (
  user_id,
  live_prediction_id,
  notification_id
)
select distinct
  s.user_id,
  lp.id,
  null::bigint
from public.live_predictions lp
join public.user_live_subscriptions s
  on lp.published_at >= s.starts_at
 and lp.published_at <= s.expires_at
join public.subscription_plans p
  on p.id = s.plan_id
where p.name = 'live'
  and s.status in ('active', 'past_due', 'cancelled', 'expired')
on conflict (user_id, live_prediction_id)
do nothing;

create or replace function public.create_forecast_notification(
  p_forecast_card_id bigint
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_forecast public.forecast_cards%rowtype;
  v_notification_id bigint;
begin
  select *
    into v_forecast
  from public.forecast_cards
  where id = p_forecast_card_id;

  if not found then
    raise exception 'Forecast card with id % not found', p_forecast_card_id;
  end if;

  if v_forecast.type not in ('premium', 'gold') then
    return null;
  end if;

  insert into public.notifications (
    title,
    plan_type,
    forecast_card_id,
    match_time,
    coefficient
  )
  values (
    'Новый ' || initcap(v_forecast.type) || ' прогноз',
    v_forecast.type,
    v_forecast.id,
    v_forecast.start_time,
    coalesce(v_forecast.total_odds, 0)
  )
  on conflict (forecast_card_id)
  where forecast_card_id is not null
  do nothing
  returning id into v_notification_id;

  if v_notification_id is null then
    select n.id
      into v_notification_id
    from public.notifications n
    where n.forecast_card_id = p_forecast_card_id;
  end if;

  return v_notification_id;
end;
$$;

create or replace function public.create_live_prediction_notification()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_notification_id bigint;
begin
  insert into public.notifications (
    title,
    plan_type,
    forecast_card_id,
    match_time,
    coefficient
  )
  values (
    'Новый Live прогноз',
    'live',
    null,
    null,
    0
  )
  returning id into v_notification_id;

  insert into public.user_live_prediction_assignments (
    user_id,
    live_prediction_id,
    notification_id
  )
  select distinct
    s.user_id,
    new.id,
    v_notification_id
  from public.user_live_subscriptions s
  join public.subscription_plans p
    on p.id = s.plan_id
  where p.name = 'live'
    and s.status in ('active', 'past_due', 'cancelled')
    and coalesce(new.published_at, now()) >= s.starts_at
    and coalesce(new.published_at, now()) <= s.expires_at
  on conflict (user_id, live_prediction_id)
  do update
  set notification_id = excluded.notification_id;

  return new;
end;
$$;

drop trigger if exists live_predictions_after_insert_notification
on public.live_predictions;

create trigger live_predictions_after_insert_notification
after insert on public.live_predictions
for each row
execute function public.create_live_prediction_notification();

drop view if exists public.my_notifications;

alter table public.notifications
drop column if exists message;

create or replace view public.my_notifications
with (security_invoker = true)
as
select n.*
from public.notifications n
where
(
  n.forecast_card_id is not null
  and exists (
    select 1
    from public.user_forecast_assignments a
    where a.forecast_card_id = n.forecast_card_id
      and a.user_id = auth.uid()
  )
)
or
(
  n.plan_type = 'live'
  and exists (
    select 1
    from public.user_live_prediction_assignments a
    where a.notification_id = n.id
      and a.user_id = auth.uid()
  )
);

create or replace view public.my_live_predictions
with (security_invoker = true)
as
select lp.*
from public.live_predictions lp
where exists (
  select 1
  from public.user_live_prediction_assignments a
  where a.live_prediction_id = lp.id
    and a.user_id = auth.uid()
);

grant select on public.my_notifications to authenticated;
grant select on public.my_live_predictions to authenticated;

revoke execute on function public.create_forecast_notification(bigint)
from public, anon, authenticated;

revoke execute on function public.create_live_prediction_notification()
from public, anon, authenticated;