create table if not exists public.forecast_cards (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('ordinary', 'premium', 'gold', 'express')),
  total_odds numeric(8,2) not null,
  start_time timestamptz not null,
  result_status text not null default 'pending' check (result_status in ('pending', 'won', 'lost')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_forecast_cards_start_time
on public.forecast_cards(start_time desc);

alter table public.forecast_cards enable row level security;

create policy "forecast_cards are readable by everyone"
on public.forecast_cards
for select
using (true);
