create table if not exists public.teams (
  id bigint generated by default as identity primary key,

  sport text not null check (
    sport in (
      'football',
      'hockey',
      'basketball',
      'tennis',
      'mma',
      'esports'
    )
  ),

  name text not null,

  logo_url text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_teams_sport
on public.teams(sport);

alter table public.teams enable row level security;

create policy "teams are readable by everyone"
on public.teams
for select
using (true);
