alter table public.subscription_options
add column if not exists bonus_until_win boolean not null default false;

alter table public.user_forecast_credits
add column if not exists bonus_until_win boolean not null default false;

update public.user_forecast_credits c
set bonus_until_win = o.bonus_until_win
from public.subscription_options o
where o.id = c.option_id;

create table if not exists public.user_forecast_assignments (
  id bigint generated by default as identity primary key,

  user_id uuid not null
    references auth.users(id)
    on delete cascade,

  forecast_card_id bigint not null
    references public.forecast_cards(id)
    on delete cascade,

  credit_id bigint
    references public.user_forecast_credits(id)
    on delete restrict,

  bonus_id bigint,

  bonus_granted boolean not null default false,

  created_at timestamptz not null default now(),

  constraint user_forecast_assignments_one_source_check
    check (
      (credit_id is not null and bonus_id is null)
      or
      (credit_id is null and bonus_id is not null)
    ),

  constraint user_forecast_assignments_user_forecast_unique
    unique (user_id, forecast_card_id)
);

create table if not exists public.user_forecast_bonuses (
  id bigint generated by default as identity primary key,

  user_id uuid not null
    references auth.users(id)
    on delete cascade,

  source_credit_id bigint not null
    references public.user_forecast_credits(id)
    on delete restrict,

  source_assignment_id bigint not null
    references public.user_forecast_assignments(id)
    on delete restrict,

  reason text not null default 'forecast_lost',

  quantity_granted integer not null default 1,

  quantity_used integer not null default 0,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint user_forecast_bonuses_quantity_granted_check
    check (quantity_granted > 0),

  constraint user_forecast_bonuses_quantity_used_check
    check (quantity_used >= 0 and quantity_used <= quantity_granted),

  constraint user_forecast_bonuses_reason_check
    check (reason in ('forecast_lost', 'manual', 'promotion')),

  constraint user_forecast_bonuses_source_assignment_unique
    unique (source_assignment_id)
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'user_forecast_assignments_bonus_id_fk'
  ) then
    alter table public.user_forecast_assignments
    add constraint user_forecast_assignments_bonus_id_fk
    foreign key (bonus_id)
    references public.user_forecast_bonuses(id)
    on delete restrict;
  end if;
end;
$$;

create index if not exists idx_user_forecast_assignments_user_id
  on public.user_forecast_assignments(user_id);

create index if not exists idx_user_forecast_assignments_forecast_card_id
  on public.user_forecast_assignments(forecast_card_id);

create index if not exists idx_user_forecast_assignments_credit_id
  on public.user_forecast_assignments(credit_id)
  where credit_id is not null;

create index if not exists idx_user_forecast_assignments_bonus_id
  on public.user_forecast_assignments(bonus_id)
  where bonus_id is not null;

create index if not exists idx_user_forecast_bonuses_user_id
  on public.user_forecast_bonuses(user_id);

create index if not exists idx_user_forecast_bonuses_source_credit_id
  on public.user_forecast_bonuses(source_credit_id);

create index if not exists idx_user_forecast_bonuses_available
  on public.user_forecast_bonuses(user_id, source_credit_id)
  where quantity_used < quantity_granted;

create index if not exists idx_user_forecast_credits_available
  on public.user_forecast_credits(user_id, plan_id)
  where quantity_used < quantity_granted;

drop trigger if exists user_forecast_bonuses_set_updated_at
on public.user_forecast_bonuses;

create trigger user_forecast_bonuses_set_updated_at
before update on public.user_forecast_bonuses
for each row
execute function public.set_updated_at();

alter table public.user_forecast_assignments enable row level security;
alter table public.user_forecast_bonuses enable row level security;

drop policy if exists "Users can view own forecast assignments"
on public.user_forecast_assignments;

create policy "Users can view own forecast assignments"
on public.user_forecast_assignments
for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can view own forecast bonuses"
on public.user_forecast_bonuses;

create policy "Users can view own forecast bonuses"
on public.user_forecast_bonuses
for select
to authenticated
using ((select auth.uid()) = user_id);

create or replace view public.user_forecast_balances
with (security_invoker = true)
as
select
  balance_rows.user_id,
  balance_rows.plan_id,
  sum(balance_rows.paid_remaining)::integer as paid_remaining,
  sum(balance_rows.bonus_remaining)::integer as bonus_remaining,
  sum(balance_rows.paid_remaining + balance_rows.bonus_remaining)::integer as total_remaining
from (
  select
    c.user_id,
    c.plan_id,
    greatest(c.quantity_granted - c.quantity_used, 0) as paid_remaining,
    0 as bonus_remaining
  from public.user_forecast_credits c

  union all

  select
    b.user_id,
    c.plan_id,
    0 as paid_remaining,
    greatest(b.quantity_granted - b.quantity_used, 0) as bonus_remaining
  from public.user_forecast_bonuses b
  join public.user_forecast_credits c
    on c.id = b.source_credit_id
) balance_rows
group by
  balance_rows.user_id,
  balance_rows.plan_id;