create table if not exists public.subscription_plans (
  id bigint generated by default as identity primary key,

  name text not null,

  subtitle text,

  feature_1 text,
  feature_2 text,
  feature_3 text,
  feature_4 text,
  feature_5 text,

  sort_order int not null default 1,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_subscription_plans_sort_order
on public.subscription_plans(sort_order);

alter table public.subscription_plans enable row level security;

create policy "subscription_plans are readable by everyone"
on public.subscription_plans
for select
using (true);
