create table if not exists public.learning_basics (
  id bigint generated by default as identity primary key,

  title text not null,
  description text not null,

  sort_order int not null default 1,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_learning_basics_sort_order
on public.learning_basics(sort_order);

alter table public.learning_basics enable row level security;

create policy "learning_basics are readable by everyone"
on public.learning_basics
for select
using (true);
