create table if not exists public.forecast_events (
  id bigint generated by default as identity primary key,

  forecast_card_id bigint not null
    references public.forecast_cards(id)
    on delete cascade,

  sport text not null check (
    sport in (
      'football',
      'hockey',
      'basketball',
      'tennis',
      'mma',
      'esports'
    )
  ),

  league text not null,

  home_team_id bigint not null
    references public.teams(id),

  away_team_id bigint not null
    references public.teams(id),

  event_time timestamptz not null,

  bet_market text not null,
  odds numeric(8,2) not null,

  result_status text not null default 'pending'
    check (result_status in ('pending', 'won', 'lost')),

  sort_order int not null default 1,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_forecast_events_card_id
on public.forecast_events(forecast_card_id);

create index if not exists idx_forecast_events_event_time
on public.forecast_events(event_time desc);

alter table public.forecast_events enable row level security;

create policy "forecast_events are readable by everyone"
on public.forecast_events
for select
using (true);
