create table if not exists public.notifications (
  id bigint generated by default as identity primary key,

  title text not null,
  message text not null,

  plan_type text not null
    check (plan_type in ('premium', 'gold', 'live')),

  forecast_card_id bigint
    references public.forecast_cards(id)
    on delete set null,

  created_at timestamptz not null default now()
);

create index if not exists idx_notifications_created_at
on public.notifications(created_at desc);

create index if not exists idx_notifications_plan_type
on public.notifications(plan_type);

create index if not exists idx_notifications_forecast_card_id
on public.notifications(forecast_card_id);

alter table public.notifications enable row level security;

drop policy if exists "notifications are readable by everyone"
on public.notifications;

create policy "notifications are readable by everyone"
on public.notifications
for select
using (true);