create table if not exists public.learning_tips (
  id bigint generated by default as identity primary key,

  title text not null,
  description text not null,

  sort_order int not null default 1,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_learning_tips_sort_order
on public.learning_tips(sort_order);

alter table public.learning_tips enable row level security;

create policy "learning_tips are readable by everyone"
on public.learning_tips
for select
using (true);
