create table if not exists public.payments (
  id bigint generated by default as identity primary key,

  user_id uuid not null
    references auth.users(id)
    on delete restrict,

  option_id bigint not null
    references public.subscription_options(id)
    on delete restrict,

  provider text not null default 'cloudpayments',

  status text not null default 'pending'
    check (
      status in (
        'pending',
        'authorized',
        'paid',
        'failed',
        'cancelled',
        'refunded'
      )
    ),

  amount numeric(12, 2) not null
    check (amount >= 0),

  currency char(3) not null default 'RUB',

  invoice_id text not null,
  provider_transaction_id bigint,

  payment_type text not null
    check (
      payment_type in (
        'one_time',
        'subscription_initial',
        'subscription_recurring'
      )
    ),

  parent_payment_id bigint
    references public.payments(id)
    on delete set null,

  failure_code text,
  failure_message text,

  provider_payload jsonb,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  paid_at timestamptz,
  failed_at timestamptz,
  refunded_at timestamptz,

  constraint payments_invoice_id_unique
    unique (invoice_id),

  constraint payments_provider_transaction_unique
    unique (provider_transaction_id)
);

create index if not exists payments_user_id_idx
  on public.payments(user_id);

create index if not exists payments_option_id_idx
  on public.payments(option_id);

create index if not exists payments_status_idx
  on public.payments(status);

create index if not exists payments_parent_payment_id_idx
  on public.payments(parent_payment_id);

create index if not exists payments_created_at_idx
  on public.payments(created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists payments_set_updated_at on public.payments;

create trigger payments_set_updated_at
before update on public.payments
for each row
execute function public.set_updated_at();

alter table public.payments enable row level security;

drop policy if exists "Users can view own payments"
on public.payments;

create policy "Users can view own payments"
on public.payments
for select
to authenticated
using ((select auth.uid()) = user_id);