create table if not exists public.user_live_subscriptions (
  id bigint generated by default as identity primary key,

  user_id uuid not null
    references auth.users(id)
    on delete cascade,

  plan_id bigint not null
    references public.subscription_plans(id)
    on delete restrict,

  option_id bigint not null
    references public.subscription_options(id)
    on delete restrict,

  payment_id bigint not null
    references public.payments(id)
    on delete restrict,

  status text not null default 'active'
    check (status in ('active', 'past_due', 'cancelled', 'expired')),

  starts_at timestamptz not null default now(),
  expires_at timestamptz not null,

  provider text not null default 'cloudpayments',
  provider_subscription_id text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint user_live_subscriptions_payment_id_unique
    unique (payment_id)
);

create index if not exists user_live_subscriptions_user_id_idx
  on public.user_live_subscriptions(user_id);

create index if not exists user_live_subscriptions_expires_at_idx
  on public.user_live_subscriptions(expires_at);

create unique index if not exists user_live_subscriptions_provider_subscription_id_unique
  on public.user_live_subscriptions(provider, provider_subscription_id)
  where provider_subscription_id is not null;

drop trigger if exists user_live_subscriptions_set_updated_at
on public.user_live_subscriptions;

create trigger user_live_subscriptions_set_updated_at
before update on public.user_live_subscriptions
for each row
execute function public.set_updated_at();

alter table public.user_live_subscriptions enable row level security;

drop policy if exists "Users can view own live subscriptions"
on public.user_live_subscriptions;

create policy "Users can view own live subscriptions"
on public.user_live_subscriptions
for select
to authenticated
using ((select auth.uid()) = user_id);

create table if not exists public.user_forecast_credits (
  id bigint generated by default as identity primary key,

  user_id uuid not null
    references auth.users(id)
    on delete cascade,

  plan_id bigint not null
    references public.subscription_plans(id)
    on delete restrict,

  option_id bigint not null
    references public.subscription_options(id)
    on delete restrict,

  payment_id bigint not null
    references public.payments(id)
    on delete restrict,

  quantity_granted integer not null
    check (quantity_granted > 0),

  quantity_used integer not null default 0
    check (quantity_used >= 0),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint user_forecast_credits_payment_id_unique
    unique (payment_id),

  constraint user_forecast_credits_quantity_used_lte_granted_check
    check (quantity_used <= quantity_granted)
);

create index if not exists user_forecast_credits_user_id_idx
  on public.user_forecast_credits(user_id);

create index if not exists user_forecast_credits_plan_id_idx
  on public.user_forecast_credits(plan_id);

drop trigger if exists user_forecast_credits_set_updated_at
on public.user_forecast_credits;

create trigger user_forecast_credits_set_updated_at
before update on public.user_forecast_credits
for each row
execute function public.set_updated_at();

alter table public.user_forecast_credits enable row level security;

drop policy if exists "Users can view own forecast credits"
on public.user_forecast_credits;

create policy "Users can view own forecast credits"
on public.user_forecast_credits
for select
to authenticated
using ((select auth.uid()) = user_id);