create table if not exists public.subscription_options (
  id bigint generated by default as identity primary key,

  plan_id bigint not null
    references public.subscription_plans(id)
    on delete cascade,

  name text not null,

  price numeric(10,2) not null,

  quantity int not null,

  unit_type text not null
    check (unit_type in ('forecast', 'week', 'month')),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_subscription_options_plan_id
on public.subscription_options(plan_id);

alter table public.subscription_options enable row level security;

create policy "subscription_options are readable by everyone"
on public.subscription_options
for select
using (true);
